### ISSUE TITLE
classification

### ISSUE THREAD

**Issue by big-rain** [marissaweis/ssl_neuron#1]
Where is the code in the algorithm evaluation index section (classification, knn)

**Comment by marissaweis** [comment]
Thank you for the interest in our work!
For evaluation, we extracted the latent embeddings per sample for the unaugmented graphs (see `ssl_neuron/demos/model_inference.ipynb` for example code) and used these as input features for the k-NN classification. We used the `KNeighborsClassifier` from the sklearn package using five nearest neighbors (if not reported otherwise). 
For comparison with previous works, we followed their evaluation whenever code was available.
